title: Alekhya Duba
description: MS in Computer Engineering (May'23) @ Texas A&M University, College Station, TX

# navbar-links:
#   email: "alekhya.duba@tamu.edu"
#   Resources:
#     - Beautiful Jekyll: "https://beautifuljekyll.com"
#     - Learn markdown: "https://www.markdowntutorial.com/"
#   Author's home: "https://deanattali.com"

# social-network-links:
#   email: "alekhya.duba@tamu.edu"
# #  rss: true  # remove this line if you don't want to show an RSS link at the bottom
#   instagram: alekhya.shreedhar
#   linkedin: alekhya.duba


theme: jekyll-theme-minimal



# plugins:
#   - jekyll-paginate
#   - jekyll-sitemap
