title: Alekhya Duba
description: MS in Computer Engineering (May'23) @ Texas A&M University, College Station, TX
#author:
#  name: alekhyaduba
#  email: alekhya.duba@tamu.edu
#social_links:
#  linkedin: https://www.linkedin.com/in/alekhya-duba/
#linkedin_username: https://www.linkedin.com/in/alekhya-duba/
social-network-links:
  email: "alekhya.duba@tamu.edu"
#  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  instagram: alekhya.shreedhar
  linkedin: alekhya.duba


theme: jekyll-theme-minimal

#
#title: Alekhya Duba
#author:
#  name: alekhyaduba
#  email: alekhya.duba@tamu.edu
#description: > # this means to ignore newlines until "show_excerpts:"
#  MS in Computer Engineering (May'23) @ Texas A&M University, College Station, TX.
#
#
#show_excerpts: false # set to true to show excerpts on the homepage
#
## Minima date format
## refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
#minima:
#  date_format: "%b %-d, %Y"
#
#  # generate social links in footer
#  social_links:
##    twitter: jekyllrb
#    github:  jekyll
#    # devto: jekyll
#    # dribbble: jekyll
#    # facebook: jekyll
#    # flickr:   jekyll
#    # instagram: jekyll
#     linkedin: jekyll
#    # pinterest: jekyll
#    # youtube: jekyll
#    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
#    # youtube_channel_name: CloudCannon
#    # telegram: jekyll
#    # googleplus: +jekyll
#    # microdotblog: jekyll
#    # keybase: jekyll
#
#    # Mastodon instances
#    # mastodon:
#    # - username: jekyll
#    #   instance: example.com
#    # - username: jekyll2
#    #   instance: example.com
#
#    # GitLab instances
#    # gitlab:
#    # - username: jekyll
#    #   instance: example.com
#    # - username: jekyll2
#    #   instance: example.com
#
## If you want to link only specific pages in your header, uncomment
## this and add the path to the pages in order as they should show up
##header_pages:
## - about.md
#
## Build settings
#theme: minima
#
#plugins:
# - jekyll-feed
# - jekyll-seo-tag
#


plugins:
  - jekyll-paginate
  - jekyll-sitemap
