title: Alekhya Duba
description: MS in Computer Engineering (Expected Graduation - May'23) @ Texas A&M University, College Station, TX
author:
  name: alekhyaduba
  email: alekhya.duba@tamu.edu
social_links:
  linkedin: https://www.linkedin.com/in/alekhya-duba/
linkedin_username: https://www.linkedin.com/in/alekhya-duba/
theme: jekyll-theme-minimal

